version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
        environment:
          database__port: "5432"
<% if (database) { %>
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: "<%= path %>"
<% } %>
    steps:
      - checkout
      - run: npm install
      - run: npm test
